/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'tertiary': '#b9c7df',
        'on-primary': '#412d00',
        'on-tertiary-fixed': '#0d1c2e',
        'outline-variant': '#45464c',
        'surface': '#0c1322',
        'on-secondary': '#263143',
        'on-secondary-container': '#aeb9d0',
        'on-tertiary-fixed-variant': '#3a485b',
        'outline': '#909097',
        'inverse-on-surface': '#293041',
        'on-primary-fixed-variant': '#5d4201',
        'on-primary-container': '#9a7836',
        'secondary-container': '#3e495d',
        'surface-container-low': '#151b2b',
        'on-tertiary': '#233144',
        'primary-fixed': '#ffdea5',
        'primary-container': '#1b1000',
        'tertiary-fixed-dim': '#b9c7df',
        'tertiary-fixed': '#d5e3fc',
        'on-error': '#690005',
        'error': '#ffb4ab',
        'surface-bright': '#32394a',
        'surface-dim': '#0c1322',
        'primary': '#e9c176',
        'background': '#0c1322',
        'surface-variant': '#2e3545',
        'surface-tint': '#e9c176',
        'on-primary-fixed': '#261900',
        'secondary-fixed-dim': '#bcc7de',
        'on-secondary-fixed': '#111c2d',
        'surface-container-high': '#232a3a',
        'surface-container-highest': '#2e3545',
        'on-surface-variant': '#c6c6cd',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#d8e3fb',
        'on-background': '#dce2f8',
        'secondary': '#bcc7de',
        'on-tertiary-container': '#707e94',
        'surface-container': '#191f2f',
        'on-surface': '#dce2f8',
        'surface-container-lowest': '#070e1d',
        'error-container': '#93000a',
        'on-secondary-fixed-variant': '#3c475a',
        'inverse-primary': '#775a19',
        'primary-fixed-dim': '#e9c176',
        'inverse-surface': '#dce2f8',
        'tertiary-container': '#041324',
        'primary-dark': '#D4AF37',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
